<h1>Uso básico de ServiceManager</h1>
<pre>
<code class="php">
    class Object {

        private $id;

        public function __construct() {
            $this->id = 100;
        }

        public function setId($id) {
            $this->id = $id;
        }

        public function getId() {
            return $this->id;
        }

    }
</code>
<code class="php">
    $sm = new \Zend\ServiceManager\ServiceManager();
    $sm->setInvokableClass('invokable-object', 'Application\ServiceManager\Object');
    $id = $sm->get('invokable-object');
</code>
</pre>
<hr>
<h6>El valor de la variable es : </h6>
<?php Zend\Debug\Debug::dump($this->id) ?>
<p class="text-warning">Observamos que invocamos a la clase por medio de su dirección</p>
<br>
<a href="/application/service-manager/implementation">Volver atrás</a>