<h1>Uso básico de ServiceManager</h1>
<pre>
<code class="php">
    class Object {

        private $id;

        public function __construct() {
            $this->id = 100;
        }

        public function setId($id) {
            $this->id = $id;
        }

        public function getId() {
            return $this->id;
        }

    }
</code>
<code class="php">
    $sm = new \Zend\ServiceManager\ServiceManager();
    $response = array('before' => 0, 'after' => 0);

    // Setting a new object
    $object = new Object();
    $sm->setService('object', $object);
    // Getting object from the service manager
    $objectService1 = $sm->get('object');
    // Getting id from object
    $response['before'] = $objectService1->getId();
    // Setting a new 500 id to object
    $objectService1->setId(500);
    // Getting object from the service manager
    $objectService2 = $sm->get('object');
    // Getting id from object
    $response['after'] = $objectService2->getId();
</code>
</pre>
<hr>
<h6>El valor de array es : </h6>
<?php Zend\Debug\Debug::dump($this->array) ?>
<p class="text-warning">Observamos que la instancia que se almacena en el ServiceManager es la misma para todo el proceso</p>
<br>
<a href="/application/service-manager/implementation">Volver atrás</a>