<h1>Service Manager en Zend Framework 2</h1>
<a href="/application/service-manager/index">Volver atrás</a>
<hr>
<p>
    El componente implementa la interface :
    <pre>Zend\ServiceManager\ServiceLocatorInterface</pre>

    El componente está ubicado en :
    <pre>Zend\ServiceManager\ServiceManager</pre>
</p>

<h4>Ejemplos sobre ServiceManager</h4>

<ul>
    <li><a href="/application/service-manager/example1">Service registration - Ejemplo básico setService / get</a></li>
    <li><a href="/application/service-manager/example2">Service registration - ¿Es la misma instancia?</a></li>
    <li><a href="/application/service-manager/example3">Lazy-loaded service objects - Ejemplo básico setInvokableClass / get</a></li>
    <li><a href="/application/service-manager/example4">Lazy-loaded service objects - ¿Es la misma instancia?</a></li>
    <li><a href="/application/service-manager/example5">Service factories - Ejemplo básico de setFactory / get</a></li>
    <li><a href="/application/service-manager/example6">Service factories - ¿Es la misma instancia?</a></li>
    <li><a href="/application/service-manager/example7">Service Manager - shared (compartiendo)</a></li>
    <li><a href="/application/service-manager/example8">Abstract factories - Ejemplo básico addAbstractFactory / get </a></li>
</ul>