<h1>Service Manager en Zend Framework 2</h1>
<a href="/application/service-manager/index">Volver atrás</a>
<hr>
<p>
    El componente implementa la interface :
    <pre>Zend\ServiceManager\ServiceLocatorInterface</pre>

    El componente está ubicado en :
    <pre>Zend\ServiceManager\ServiceManager</pre>
</p>

<h4>Ejemplos sobre ServiceManager</h4>

<ul>
    <li><a href="/application/service-manager/example1">Service registration - Ejemplo básico setService / get</a></li>
    <li><a href="/application/service-manager/example2">Service registration - ¿Es el mismo objeto?</a></li>
    <li><a href="/application/service-manager/example3">Lazy-loaded service objects - Ejemplo de service manager usando invocaciones (invokables)</a></li>
</ul>